#!/bin/bash -x

if [ "$1" == "build" ]; then
  service postgresql start
  su postgres createdb builder
  go get bitbucket.org/liamstask/goose/cmd/goose
  goose up
  go test
else
  docker build -t AndrewVos/builder .
  docker run -i -v `pwd`:/gopath/src/github.com/AndrewVos/builder \
                     AndrewVos/builder ./Builderfile build
fi

