#!/bin/bash -x

if [ "$1" == "build" ]; then
  service postgresql start
  su postgres -c "createuser -d -s -r -e root"
  su postgres -c "createdb builder"
  go get bitbucket.org/liamstask/goose/cmd/goose
  goose up
  go get -u
  go test
else
  docker build -t AndrewVos/builder .
  docker run -i -v `pwd`:/gopath/src/github.com/AndrewVos/builder \
                     AndrewVos/builder ./Builderfile build
fi
